In [8]:
import pandas as pd

# read from file
df = pd.read_csv(r"C:\Users\itsra\Desktop\jupyter_project\netflix_titles.csv", encoding='latin1')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
Unnamed: 12     8809
Unnamed: 13     8809
Unnamed: 14     8809
Unnamed: 15     8809
Unnamed: 16     8809
Unnamed: 17     8809
Unnamed: 18     8809
Unnamed: 19     8809
Unnamed: 20     8809
Unnamed: 21     8809
Unnamed: 22     8809
Unnamed: 23     8809
Unnamed: 24     8809
Unnamed: 25     8809
dtype: int64

In [11]:
df.duplicated().sum()

df.drop_duplicates(inplace=True)

In [12]:
df['country'] = df['country'].str.lower().str.strip()
df['type'] = df['type'].str.upper()

In [15]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [16]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [22]:
df['release_year'] = df['release_year'].astype(int)

In [19]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 8799 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8799 non-null   object
 1   type          8799 non-null   object
 2   title         8799 non-null   object
 3   director      8799 non-null   object
 4   cast          7974 non-null   object
 5   country       8799 non-null   object
 6   date_added    8711 non-null   datetime64[ns]
 7   release_year  8799 non-null   int64
 8   rating        8795 non-null   object
 9   duration      8796 non-null   object
 10  listed_in     8799 non-null   object
 11  description   8799 non-null   object
 12  unnamed:_12   0 non-null      float64
 13  unnamed:_13   0 non-null      float64
 14  unnamed:_14   0 non-null      float64
 15  unnamed:_15   0 non-null      float64
 16  unnamed:_16   0 non-null      float64
 17  unnamed:_17   0 non-null      float64
 18  unnamed:_18   0 non-null      float64
 19  unnamed:_19   0 non-null      float64
 20  unnamed:_20   0 non-null      float64
 21  unnamed:_21   0 non-null      float64
 22  unnamed:_22   0 non-null      float64
 23  unnamed:_23   0 non-null      float64
 24  unnamed:_24   0 non-null      float64
 25  unnamed:_25   0 non-null      float64
dtypes: datetime64[ns](1), float64(14), int64(1), object(10)
memory usage: 1.8+ MB

show_id            0
type               0
title              0
director           0
cast             825
country            0
date_added        88
release_year       0
rating             4
duration           3
listed_in          0
description        0
unnamed:_12     8799
unnamed:_13     8799
unnamed:_14     8799
unnamed:_15     8799
unnamed:_16     8799
unnamed:_17     8799
unnamed:_18     8799
unnamed:_19     8799
unnamed:_20     8799
unnamed:_21     8799
unnamed:_22     8799
unnamed:_23     8799
unnamed:_24     8799
unnamed:_25     8799
dtype: int64

In [20]:
df.to_csv("cleaned_netflix.csv", index=False)

In [21]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,unnamed:_16,unnamed:_17,unnamed:_18,unnamed:_19,unnamed:_20,unnamed:_21,unnamed:_22,unnamed:_23,unnamed:_24,unnamed:_25
0,s1,MOVIE,Dick Johnson Is Dead,Kirsten Johnson,NaN,united states,2021-09-25,2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV SHOW,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,2021-09-24,2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV SHOW,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",not available,2021-09-24,2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV SHOW,Jailbirds New Orleans,Unknown,NaN,not available,2021-09-24,2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV SHOW,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,2021-09-24,2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN